name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Setup .env file
        run: |
          cp .env.example .env
          php artisan key:generate
          # force correct DB config
          sed -i 's/DB_HOST=.*/DB_HOST=mysql/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=laravel/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=root/' .env

      - name: Verify DB connection
        run: |
          sudo apt-get update && sudo apt-get install -y default-mysql-client
          for i in {1..30}; do
            if mysql -hmysql -uroot -proot -e "SHOW DATABASES;" > /dev/null 2>&1; then
              echo "✅ MySQL is ready!"
              break
            fi
            echo "⏳ Waiting for MySQL..."
            sleep 5
          done

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
