name: Laravel CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      # Step 1: Checkout project
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_mysql
          coverage: none

      # Step 3: Install dependencies
      - name: Install composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      # Step 4: Prepare Laravel environment
      - name: Prepare environment file
        - name: Prepare environment file
        run: |
          cp .env.example .env
          php artisan key:generate

      # Step 5: Wait until MySQL is ready
      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -hmysql -uroot -proot --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for database connection..."
            sleep 5
          done

      # Step 6: Run database migrations
      - name: Run migrations
        run: php artisan migrate --force

      # Step 7: Run PHPUnit tests
      - name: Run tests
        run: php artisan test
